import styles from '../styles/components/_layout.module.scss';
import Head from 'next/head';
import { BackButton } from '../components';
import Image from 'next/image';

export function Layout({ children, backButton }) {
  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          {backButton ? (
            <BackButton />
          ) : (
            <>
              <div className={styles.headerImageWrapper}>
                <Image
                  className={styles.header__image}
                  srcSet="/images/rick-and-morty-312.jpg 312w, /images/rick-and-morty-600.jpg 600w"
                  alt="Rick and Morty"
                  src="/images/rick-and-morty-600.jpg"
                  width={600}
                  height={200}
                  sizes="(min-width: 1440px) 600px,
                  312px"
                  priority
                />
              </div>
            </>
          )}
        </header>
        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
}
