import styles from '../styles/components/_layout.module.scss';
import Head from 'next/head';

export function Layout({ children, character }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>{character ? <></> : <></>}</header>
      <main>{children}</main>
    </div>
  );
}
