import styles from '../styles/components/_layout.module.scss';
import Head from 'next/head';
import { BackButton } from '../components';

export function Layout({ children, backButton }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>{backButton ? <BackButton /> : <></>}</header>
      <main>{children}</main>
    </div>
  );
}
